/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package belajarjava;

/**
 *
 * @author Maya
 */
public class Modul5 extends javax.swing.JFrame {

    /**
     * Creates new form Modul5
     */
    public Modul5() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NamaField = new javax.swing.JTextField();
        AlamatField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Minuman1 = new javax.swing.JCheckBox();
        Minuman2 = new javax.swing.JCheckBox();
        Minuman3 = new javax.swing.JCheckBox();
        Makanan1 = new javax.swing.JCheckBox();
        Makanan2 = new javax.swing.JCheckBox();
        Makanan3 = new javax.swing.JCheckBox();
        Minuman4 = new javax.swing.JCheckBox();
        Makanan4 = new javax.swing.JCheckBox();
        PesanButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        HasilPesan = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nama");

        jLabel2.setText("Alamat");

        Minuman1.setText("Susu");
        Minuman1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Minuman1ActionPerformed(evt);
            }
        });

        Minuman2.setText("Kopi");
        Minuman2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Minuman2ActionPerformed(evt);
            }
        });

        Minuman3.setText("Teh");

        Makanan1.setText("Roti");
        Makanan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Makanan1ActionPerformed(evt);
            }
        });

        Makanan2.setText("Mie");
        Makanan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Makanan2ActionPerformed(evt);
            }
        });

        Makanan3.setText("Gorengan");

        Minuman4.setText("Jus");

        Makanan4.setText("Nasi");

        PesanButton.setText("Pesan");
        PesanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesanButtonActionPerformed(evt);
            }
        });

        HasilPesan.setColumns(20);
        HasilPesan.setRows(5);
        jScrollPane1.setViewportView(HasilPesan);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Minuman2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Minuman3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Minuman4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Makanan2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Makanan4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Makanan3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Minuman1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(Makanan1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 74, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AlamatField)
                            .addComponent(NamaField))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(layout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addComponent(PesanButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(NamaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(AlamatField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Minuman1)
                            .addComponent(Makanan1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Minuman2)
                            .addComponent(Makanan2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Minuman3)
                            .addComponent(Makanan3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Minuman4)
                            .addComponent(Makanan4)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(PesanButton)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Minuman1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Minuman1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Minuman1ActionPerformed

    private void Minuman2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Minuman2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Minuman2ActionPerformed

    private void Makanan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Makanan1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Makanan1ActionPerformed

    private void Makanan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Makanan2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Makanan2ActionPerformed

    private void PesanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesanButtonActionPerformed
     // Ambil nama dan alamat dari JTextField
    String nama = NamaField.getText();
    String alamat = AlamatField.getText();
    
    // Buat StringBuilder untuk menyusun pesan
    StringBuilder pesanan = new StringBuilder();
    
    // Tambahkan nama dan alamat ke pesan
    pesanan.append("Nama: ").append(nama).append("\n");
    pesanan.append("Alamat: ").append(alamat).append("\n\n");
    
    // Tambahkan minuman yang dipilih ke pesan
    pesanan.append("Minuman:\n");
    if (Minuman1.isSelected()) pesanan.append(" - ").append(Minuman1.getText()).append("\n");
    if (Minuman2.isSelected()) pesanan.append(" - ").append(Minuman2.getText()).append("\n");
    if (Minuman3.isSelected()) pesanan.append(" - ").append(Minuman3.getText()).append("\n");
    if (Minuman4.isSelected()) pesanan.append(" - ").append(Minuman4.getText()).append("\n");
    
    // Tambahkan makanan yang dipilih ke pesan
    pesanan.append("\nMakanan:\n");
    if (Makanan1.isSelected()) pesanan.append(" - ").append(Makanan1.getText()).append("\n");
    if (Makanan2.isSelected()) pesanan.append(" - ").append(Makanan2.getText()).append("\n");
    if (Makanan3.isSelected()) pesanan.append(" - ").append(Makanan3.getText()).append("\n");
    if (Makanan4.isSelected()) pesanan.append(" - ").append(Makanan4.getText()).append("\n");
    
    // Tampilkan pesan di JTextArea
    HasilPesan.setText(pesanan.toString());
    }//GEN-LAST:event_PesanButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modul5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modul5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modul5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modul5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modul5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AlamatField;
    private javax.swing.JTextArea HasilPesan;
    private javax.swing.JCheckBox Makanan1;
    private javax.swing.JCheckBox Makanan2;
    private javax.swing.JCheckBox Makanan3;
    private javax.swing.JCheckBox Makanan4;
    private javax.swing.JCheckBox Minuman1;
    private javax.swing.JCheckBox Minuman2;
    private javax.swing.JCheckBox Minuman3;
    private javax.swing.JCheckBox Minuman4;
    private javax.swing.JTextField NamaField;
    private javax.swing.JButton PesanButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
